name: render_templates
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  mime: ^1.0.0
  mustache_template: ^2.0.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
